[profiles.benjajaja]
user_id = "@benjajaja:qdice.wtf"

[settings]
username_display = "displayname"

[settings.image_preview]
size = { height = 20, width = 90 }

[layout]
style = "restore"

[settings.notifications]
enabled = true
show_message = true

[macros.normal]
"<C-J>" = "gt"
"<C-K>" = "gT"
"-" = ":tab chats<Enter>"
"<C-C>" = ":tabclose<Enter>"
